development:
  clients:
    default:
      database: rails50_app_development
      hosts:
        - 127.0.0.1:27017

test:
  clients:
    default:
      database: rails50_app_test
      hosts:
        - 127.0.0.1:27017
